// Generated by CoffeeScript 1.7.1
#target Bridge;
#targetengine main;
#include "./ai2ass.jsxinc";
var radioString, win;

win = new Window("palette", "Export ASS", void 0, {});

win.outputBox = win.add("edittext", [0, 0, 250, 80], "", {
  multiline: true
});

win.outputBox.graphics.font = "Comic Sans MS:12";

win.outputBox.text = "have ass, will typeset";

win.clip = win.add("Group {orientation: 'row', noclip: RadioButton { text: 'drawing', value: true }, clip: RadioButton { text: 'clip' }, iclip: RadioButton { text: 'iclip' }, bare: RadioButton { text: 'bare' } }");

win.clip.noclip.graphics.font = "Comic Sans MS:12";

win.clip.clip.graphics.font = "Comic Sans MS:12";

win.clip.iclip.graphics.font = "Comic Sans MS:12";

win.clip.bare.graphics.font = "Comic Sans MS:12";

win.collectionMethod = win.add("dropdownlist", [0, 0, 250, 20], ["collectActiveLayer", "collectInnerShadow", "collectAllLayers", "CG_collectActiveLayer"]);

win.collectionMethod.graphics.font = "Comic Sans MS:12";

win.collectionMethod.selection = 0;

win.goButton = win.add("button", void 0, "Export");

win.goButton.graphics.font = "Comic Sans MS:12";

radioString = function(radioGroup) {
  var child, _i, _len, _ref;
  _ref = radioGroup.children;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    child = _ref[_i];
    if (child.value) {
      return child.text;
    }
  }
};

win.goButton.onClick = function() {
  var bt;
  win.outputBox.active = false;
  bt = new BridgeTalk;
  bt.target = "illustrator";
  bt.body = "(" + (ai2assBackend.toString()) + ")({method:\"" + win.collectionMethod.selection.text + "\",wrapper:\"" + (radioString(win.clip)) + "\"});";
  bt.onResult = function(result) {
    win.outputBox.text = result.body.replace(/\\\\/g, "\\").replace(/\\n/g, "\n");
    return win.outputBox.active = true;
  };
  bt.onError = function(err) {
    return alert("" + err.body + " (" + a.headers["Error-Code"] + ")");
  };
  return bt.send();
};

win.show();
